<template>
  <teleport to="body">
    <a-transition-enter-y>
      <div
        v-if="modelValue"
        :class="`template`"
        style="z-index: 10;"
        class="po-fixed dark:text-grey-tint-14 text-grey-shade-14 dark:background-grey-shade-14 background-grey-tint-14 wi-min-100vw he-min-100vh wi-max-100vw he-max-100vh ov-auto py-10 di-flex ai-stretch jc-center"
      >
        <main-layout>
          <template #card>
            <div class="row he-min-100">
              <div
                class="col-1 background-grey ro-left-5 bloom-4-grey-blend-6"
                :class="`template:background-${color.name.toLocaleLowerCase()} template:bloom-4-${color.name.toLocaleLowerCase()}-blend-6`"
              ></div>
              <div class="col-11 di-flex fl-column jc-space-around pr-5">
                <div class="mb-3">
                  <div class="ml-5 mt-3 fw-6 fs-6">Tints</div>
                  <div class="ml-5 mb-3 fw-2 fs-4">
                    Tints are generated by increasing the lightness of a color.
                    The generated classes are in the format
                    <span
                      :class="`template:background-${color.name.toLocaleLowerCase()}-blend-7  `"
                      class="ro-2 py-1 px-2 fw-5"
                    >
                      {property}-{color}-tint-{value}
                    </span>
                    .
                  </div>

                  <div class="di-flex ro-right-5 ov-hidden">
                    <div
                      class="fl-grow-1 color-wrapper di-flex jc-center ai-center"
                      :class="`py-10 template:background-${name}`"
                      v-for="(hash, name) in filterColors(colorsObject, 'tint')"
                    >
                      <div
                        class="color-hover te-center"
                        :class="
                          parseInt(hash.slice(1, 7), 16) > 10230527
                            ? 'text-grey-shade-14'
                            : 'text-grey-tint-14'
                        "
                      >
                        {{ name }}
                        <br />
                        {{ hash }}
                      </div>
                    </div>
                  </div>
                </div>
                <div class="mb-3">
                  <div class="ml-5 mt-3 fw-6 fs-6">Shades</div>
                  <div class="ml-5 mb-3 fw-2 fs-4">
                    Shades are generated by decreasing the lightness of a color.
                    The generated classes are in the format
                    <span
                      :class="`template:background-${color.name.toLocaleLowerCase()}-blend-7  `"
                      class="ro-2 py-1 px-2 fw-5"
                    >
                      {property}-{color}-shade-{value}
                    </span>
                  </div>

                  <div class="di-flex ro-right-5 ov-hidden">
                    <div
                      class="fl-grow-1 color-wrapper di-flex jc-center ai-center"
                      :class="`py-10 template:background-${name}`"
                      v-for="(hash, name) in filterColors(
                        colorsObject,
                        'shade',
                      )"
                    >
                      <div
                        class="color-hover te-center"
                        :class="
                          parseInt(hash.slice(1, 7), 16) > 10230527
                            ? 'text-grey-shade-14'
                            : 'text-grey-tint-14'
                        "
                      >
                        {{ name }}
                        <br />
                        {{ hash }}
                      </div>
                    </div>
                  </div>
                </div>
                <div class="mb-3">
                  <div class="ml-5 mt-3 fw-6 fs-6">Tones</div>
                  <div class="ml-5 mb-3 fw-2 fs-4">
                    Tones are generated by decreasing the saturation of a color.
                    The generated classes are in the format
                    <span
                      :class="`template:background-${color.name.toLocaleLowerCase()}-blend-7  `"
                      class="ro-2 py-1 px-2 fw-5"
                    >
                      {property}-{color}-tone-{value}
                    </span>
                  </div>
                  <div class="di-flex ro-right-5 ov-hidden">
                    <div
                      class="fl-grow-1 color-wrapper di-flex jc-center ai-center"
                      :class="`py-10 template:background-${name}`"
                      v-for="(hash, name) in filterColors(colorsObject, 'tone')"
                    >
                      <div
                        class="color-hover te-center"
                        :class="
                          parseInt(hash.slice(1, 7), 16) > 10230527
                            ? 'text-grey-shade-14'
                            : 'text-grey-tint-14'
                        "
                      >
                        {{ name }}
                        <br />
                        {{ hash }}
                      </div>
                    </div>
                  </div>
                </div>
                <div class="mb-3">
                  <div class="ml-5 mt-3 fw-6 fs-6">Blends</div>
                  <div class="ml-5 mb-3 fw-2 fs-4">
                    Blends are generated by decreasing the opacity of a color.
                    The generated classes are in the format
                    <span
                      :class="`template:background-${color.name.toLocaleLowerCase()}-blend-7  `"
                      class="ro-2 py-1 px-2 fw-5"
                    >
                      {property}-{color}-blend-{value}
                    </span>
                  </div>
                  <div class="di-flex ro-right-5 ov-hidden png-squares">
                    <div
                      style="z-index: 2;"
                      class="fl-grow-1 color-wrapper di-flex jc-center ai-center"
                      :class="`template:background-${name}`"
                      v-for="(hash, name) in filterColors(
                        colorsObject,
                        'blend',
                      )"
                    >
                      <div
                        class="color-hover te-center"
                        :class="
                          parseInt(hash.slice(1, 7), 16) > 10230527
                            ? 'text-grey-shade-14'
                            : 'text-grey-tint-14'
                        "
                      >
                        {{ name }}
                        <br />
                        {{ hash }}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </template>
          <template #options>
            <div class="px-5">
              <div class="fs-8 dark:text-primary-tint-9 text-primary-shade-9">
                Edit color
              </div>
              <div
                class="fs-5 pb-10 dark:text-primary-tint-8 text-primary-shade-8"
              >
                Generate a color scheme from a color.
              </div>
            </div>

            <div class="px-10 pb-5">
              <a-input v-model="color.name" label="Name"></a-input>
              <div class="di-flex ai-center">
                <a-input
                  v-model="color.hash"
                  label="Color"
                  class="fl-grow-1"
                ></a-input>
                <a-color-picker
                  v-model="color.hash"
                  label="Color"
                  class="ml-4"
                ></a-color-picker>
              </div>
              <div class="mt-10">Color options</div>
              <a-row
                class="mt-2"
                cols="6 6 6 6"
                gutter="3"
                col-class="di-flex ai-center"
              >
                <template #0>
                  <a-button
                    @click="color.options.tints--"
                    template="text"
                    size="1"
                    class="fl-shrink-0"
                    rounded="4"
                  >
                    <a-icon icon="minus" color="white"></a-icon>
                  </a-button>
                  <a-input
                    v-model="color.options.tints"
                    type="number"
                    label="Tints"
                    class="fl-grow-1 mx-2 te-center"
                  ></a-input>
                  <a-button
                    template="text"
                    @click="color.options.tints++"
                    size="1"
                    rounded="4"
                    class="fl-shrink-0"
                  >
                    <a-icon icon="plus" color="white"></a-icon>
                  </a-button>
                </template>
                <template #1>
                  <a-button
                    @click="color.options.shades--"
                    template="text"
                    size="1"
                    class="fl-shrink-0"
                    rounded="4"
                  >
                    <a-icon icon="minus" color="white"></a-icon>
                  </a-button>
                  <a-input
                    v-model="color.options.shades"
                    type="number"
                    label="Shades"
                    class="fl-grow-1 mx-2 te-center"
                  ></a-input>
                  <a-button
                    template="text"
                    @click="color.options.shades++"
                    size="1"
                    rounded="4"
                    class="fl-shrink-0"
                  >
                    <a-icon icon="plus" color="white"></a-icon>
                  </a-button>
                </template>
                <template #2>
                  <a-button
                    @click="color.options.tones--"
                    template="text"
                    size="1"
                    class="fl-shrink-0"
                    rounded="4"
                  >
                    <a-icon icon="minus" color="white"></a-icon>
                  </a-button>
                  <a-input
                    v-model="color.options.tones"
                    type="number"
                    label="Tones"
                    class="fl-grow-1 mx-2 te-center"
                  ></a-input>
                  <a-button
                    template="text"
                    @click="color.options.tones++"
                    size="1"
                    rounded="4"
                    class="fl-shrink-0"
                  >
                    <a-icon icon="plus" color="white"></a-icon>
                  </a-button>
                </template>
                <template #3>
                  <a-button
                    @click="color.options.alphas--"
                    template="text"
                    size="1"
                    class="fl-shrink-0"
                    rounded="4"
                  >
                    <a-icon icon="minus" color="white"></a-icon>
                  </a-button>
                  <a-input
                    v-model="color.options.alphas"
                    type="number"
                    label="Blends"
                    class="fl-grow-1 mx-2 te-center"
                  ></a-input>
                  <a-button
                    template="text"
                    @click="color.options.alphas++"
                    size="1"
                    rounded="4"
                    class="fl-shrink-0"
                  >
                    <a-icon icon="plus" color="white"></a-icon>
                  </a-button>
                </template>
              </a-row>
            </div>
          </template>
          <template #optionsFooter>
            <div class="row">
              <a-button
                @click="emit('update:modelValue', false)"
                template="text"
                class="col mr-2"
              >
                <a-icon class="mr-1">close</a-icon>
                Cancel
              </a-button>
              <a-button @click="updateColor()" class="col ml-2">
                <a-icon class="mr-1">plus</a-icon>
                Add Color
              </a-button>
            </div>
          </template>
        </main-layout>
      </div>
    </a-transition-enter-y>
  </teleport>
</template>
<script setup lang="ts">
import {
  generateClasses,
  generateColorScheme,
  generateStyle,
  prefixClasses,
} from '@/config/functions'
import { generateColorValues, isValid } from '@/config/colors'
const { $appendStyle, $downloadStyle } = useNuxtApp()

let timer: NodeJS.Timeout
function debounce(func: Function, wait = 1000) {
  clearTimeout(timer)
  timer = setTimeout(() => {
    func()
  }, wait)
}
function debounceGenerate() {
  debounce(() => {
    generateColors()
  }, 300)
}
let emit = defineEmits(['update:modelValue', 'updateColor'])
let props = defineProps({
  modelValue: {
    type: Boolean,
    default: false,
  },
  currentColor: {
    type: Object,
    default: () => {},
  },
})

watch(
  () => props.modelValue,
  () => {
    generateColors()
  },
)
watch(
  () => props.currentColor,
  () => {
    color.value = {
      ...{
        name: 'primary',
        hash: '#ff0000',
        options: {
          tints: 10,
          shades: 10,
          alphas: 10,
          tones: 10,
        },
      },
      ...props.currentColor,
    }
  },
)
function updateColor() {
  emit('updateColor', color.value)
  emit('update:modelValue', false)
}
let color = ref({
  ...{
    name: 'primary',
    hash: '#ff0000',
    options: {
      tints: 10,
      shades: 10,
      alphas: 10,
      tones: 10,
    },
  },
  ...props.currentColor,
})
watch(
  color,
  () => {
    debounceGenerate()
  },
  { deep: true },
)
let colorsObject = ref({})

function filterColors(colorObject: object, key: string) {
  return Object.fromEntries(
    Object.entries(colorObject).filter(([property, value]) =>
      property.includes(key),
    ),
  )
}

function generateColors() {
  if (!color.value.name || !isValid(color.value.hash)) return
  colorsObject.value = generateColorValues(color.value)
  let colors = generateColorScheme(color.value)
  $appendStyle(generateClasses(prefixClasses(colors, `template .template`)))
  /*   generateStyle().then((css) => {
    $appendStyle(css)
  }) */
}
</script>
<style scoped>
.color-wrapper {
  height: 80px;
  max-height: 80px;
  flex-basis: 1px;
  transition: flex-basis 0.3s;
}
.color-wrapper:hover {
  flex-basis: 150px;
}
.color-hover {
  width: 0;
  white-space: nowrap;
  transition: opacity 0.3s, width 0.5s;
  opacity: 0;
  overflow: hidden;
}
div:hover > .color-hover {
  width: 150px;
  opacity: 1;
}
.png-squares {
  position: relative;
  background-repeat: repeat;
  background-color: #aaa;
  background-image: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2 2"><path d="M1 2V0h1v1H0v1z" fill-opacity="0.2"/></svg>');
  background-size: 20px 20px;
}
</style>
