export default function () {
  return useState('profileData', () => [
    {
      icon: 'xml',
      key: 'programming',
      name: 'Programming Languages',
      children: [
        {
          icon: 'language-html5',
          key: 'html',
          name: 'HTML',
          exp: 95,
          dateStart: '2014-02-08',
          dateWork: '2020-01-13',
        },
        {
          icon: 'language-css3',
          key: 'css',
          name: 'CSS',
          exp: 95,
          dateStart: '2014-02-08',
          dateWork: '2020-01-13',
        },
        {
          icon: 'language-javascript',
          key: 'js',
          name: 'JavaScript',
          exp: 98,
          dateStart: '2014-02-08',
          dateWork: '2020-01-13',
        },
        {
          icon: 'language-cpp',
          key: 'cpp',
          name: 'C++',
          exp: 50,
          dateStart: '2017-03-13',
          dateRange: ['2017-03-13', '2018-03-13'],
        },
        {
          icon: 'language-typescript',
          key: 'ts',
          name: 'TypeScript',
          exp: 50,
          dateStart: '2021-07-01',
          dateRange: ['2021-07-01', '2022-06-01'],
        },
        {
          icon: 'language-lua',
          key: 'lua',
          name: 'Lua',
          exp: 40,
          dateStart: '2021-03-01',
          dateRange: ['2021-03-01', '2021-07-01'],
        },
        {
          icon: 'language-php',
          key: 'php',
          name: 'PHP',
          exp: 50,
          dateStart: '2014-02-08',
          dateWork: '2020-01-13',
        },
        {
          icon: 'database',
          key: 'sql',
          name: 'Sql and NoSql',
          exp: 40,
          dateStart: '2014-02-08',
          dateWork: '2020-01-13',
        },
      ],
    },
    {
      icon: 'file-code',
      key: 'frameworks',
      name: 'Frameworks/Libs',
      children: [
        {
          icon: 'nodejs',
          name: 'Node',
          key: 'node',
          exp: 80,
          dateStart: '2020-01-13',
          dateWork: '2020-01-13',
        },
        {
          icon: 'vuejs',
          name: 'Vue',
          key: 'vue',
          exp: 100,
          dateStart: '2020-01-13',
          dateWork: '2020-01-13',
        },
        {
          icon: 'vuejs',
          name: 'Vue3',
          key: 'vue',
          exp: 65,
          dateStart: '2021-11-01',
          dateWork: '2021-11-01',
        },
        {
          icon: 'nuxt',
          name: 'Nuxt',
          key: 'nuxt',
          exp: 100,
          dateStart: '2021-07-01',
          dateWork: '2021-07-01',
        },
        {
          icon: 'nuxt',
          name: 'Nuxt3',
          key: 'nuxt',
          exp: 70,
          dateStart: '2021-11-01',
          dateWork: '2021-11-01',
        },
        {
          icon: 'vuetify',
          name: 'Vuetify',
          key: 'vuetify',
          exp: 100,
          dateStart: '2021-07-01',
          dateWork: '2021-07-01',
        },
        {
          icon: 'nativescript',
          name: 'Vue Native',
          key: 'native',
          exp: 40,
          dateStart: '2021-03-01',
          dateRange: ['2021-03-01', '2021-04-01'],
        },
        {
          icon: 'bootstrap',
          name: 'Bootstrap',
          key: 'bootstrap',
          exp: 100,
          dateStart: '2020-01-13',
          dateRange: ['2020-01-13', '2021-07-01'],
        },
        {
          icon: 'sass',
          name: 'Sass',
          key: 'sass',
          exp: 95,
          dateStart: '2020-01-13',
          dateWork: '2020-01-13',
        },
        {
          icon: 'laravel',
          name: 'Laravel',
          key: 'laravel',
          exp: 60,
          dateStart: '2020-01-13',
          dateWork: '2020-01-13',
        },
      ],
    },
    {
      icon: 'pencil-ruler',
      key: 'design',
      name: 'Design',
      children: [
        {
          icon: 'image-edit',
          name: 'Photoshop',
          key: 'ps',
          exp: 95,
          dateStart: '2017-01-01',
          dateWork: '2017-01-01',
        },
        {
          icon: 'brush',
          name: 'Illustrator',
          key: 'il',
          exp: 85,
          dateStart: '2019-01-01',
          dateWork: '2019-01-01',
        },
        {
          icon: 'video',
          name: 'Premiere',
          key: 'pr',
          exp: 60,
          dateStart: '2019-01-01',
          dateRange: ['2019-01-01', '2019-03-01'],
        },
      ],
    },
    {
      icon: 'school',
      key: 'education',
      name: 'Education',
      children: [
        {
          icon: 'code-braces',
          name: 'Web Design Course',
          key: 'pro',
          dateStart: '2014-02-01',
          dateRange: ['2014-01-01', '2015-01-01'],
        },
        {
          icon: 'cog',
          name: 'Control and automation engineering',
          key: 'eng',
          dateStart: '2017-03-01',
        },
      ],
    },
    {
      icon: 'dots-horizontal',
      key: 'other',
      name: 'Other',
      children: [
        {
          icon: 'git',
          name: 'Git',
          key: 'git',
          exp: 100,
          dateStart: '2020-01-13',
          dateWork: '2020-01-13',
        },
        {
          icon: 'aws',
          name: 'Amazon Web Services',
          key: 'aws',
          exp: 70,
          dateStart: '2020-01-13',
          dateWork: '2020-01-13',
        },
        {
          icon: 'sitemap',
          name: 'Scrum and Workflow',
          key: 'scrum',
          exp: 90,
          dateStart: '2020-01-13',
          dateWork: '2020-01-13',
        },
        {
          icon: 'language-markdown',
          name: 'Documentation',
          key: 'doc',
          exp: 80,
          dateStart: '2020-08-13',
          dateWork: '2020-08-13',
        },
      ],
    },
  ])
}
